// utils/projectData.ts
export const projectData = [
  {
    id: 1,
    name: "Website Redesign",
    status: "In Progress",
    priority: "High",
    description: "Redesign the company website to improve UI/UX and mobile responsiveness.",
    duedate: "2024-10-15",
  },
  {
    id: 2,
    name: "Marketing Campaign",
    status: "Pending",
    priority: "Medium",
    description: "Develop a digital marketing strategy for the upcoming product launch.",
    duedate: "2024-11-01",
  },
  {
    id: 3,
    name: "Mobile App Development",
    status: "In Progress",
    priority: "High",
    description: "Create a cross-platform mobile app for better user engagement.",
    duedate: "2024-12-30",
  },
  {
    id: 4,
    name: "Customer Feedback System",
    status: "Completed",
    priority: "Low",
    description: "Build and integrate a customer feedback system into the web platform.",
    duedate: "2024-09-05",
  },
  {
    id: 5,
    name: "Cloud Migration",
    status: "In Progress",
    priority: "High",
    description: "Migrate all on-premise infrastructure to cloud services for scalability.",
    duedate: "2024-12-01",
  },
  {
    id: 6,
    name: "Data Analytics Dashboard",
    status: "Pending",
    priority: "Medium",
    description: "Develop a dashboard for real-time data analytics and reporting.",
    duedate: "2024-11-15",
  },
];
